version: "3.4"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: runtime
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ./backend
      target: runtime
    environment:
      - MONGODB_URL=mongodb://docker:mongopw@mongodb:27017
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    restart: always
    # volumes:
    #   - data:/data/db
